apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: hdfs.csi.varga
  name: hdfsexample
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: hdfs.csi.varga
    volumeHandle: "hdfs://xxx:9090/path"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      auth: kerberos
    nodeStageSecretRef:
      name: hdfs-secret
      namespace: expense
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl