apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdfs-sc
provisioner: hdfs.csi.varga
parameters:
  location: "hdfs://xxx:9090"
  secretName: "hdfs-secret"
  secretNamespace: "expense"
reclaimPolicy: Delete # Retain
volumeBindingMode: WaitForFirstConsumer # Immediate
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true