replicaCount: 1
image:
  repository: ghcr.io/varga-foundation/vorath
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

nodeSelector: {}

tolerations: []

affinity: {}

grpcPort: 50051
csiPluginName: hdfs-csi-driver